project:
  type: website
  output-dir: docs  # For GitHub Pages

website:
  title: "Plant Heat Tolerance Database"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Data
        href: data.qmd

format:
  html:
    theme: cosmo
    css: styles.css
