---
title: ""
format: html
---

# ðŸŒ± Plant Heat Tolerance DatabaseðŸŒ¡ï¸

This site accompanies the data paper:\
**A database of plant heat tolerances and methodological matters**

The dataset includes 3,000+ records of heat tolerance traits across 1,700+ plant taxa.\

## ðŸ”—Links:

-   [Download the dataset](http://datadryad.org/share/LINK_NOT_FOR_PUBLICATION/k7Zb6yQwimY9E84FZQ4NILE1j7SJK8vraLRsVG1zyn8)
-   [Link to the bioRxiv paper](https://www.biorxiv.org/content/10.1101/2025.09.14.676187v1)

## ðŸ“¤ Contribute to the Heat Tolerance Database

We welcome data submissions of plant heat tolerances from other scientists. If you'd like to share your data to this public data set, follow the instructions:

### Step 1: Download the CSV Template

Please use the template below to format your data correctly: [Download CSV Template](https://drive.google.com/file/d/1x9KkK7Rlx6qkzuW9bgFiQXjEZvzaViPG/view?usp=drive_link)

### Step 2: Submit Your Data

Once your CSV is ready, please upload it via [this secure Google Form link](https://docs.google.com/forms/d/e/1FAIpQLSeO2FrMcVU3YP8t2_Fx0lt6BJ-Qx0gRl0D3lZaumzlpD9Tvmw/viewform?usp=header).

Submissions will be periodically reviewed and merged into the main database for all to access. A link to the updated database will be provided here once updates are made. 

## ðŸ“œCitation

If you use this dataset, please cite:

> Timothy M Perez, Alyssa Kullberg, Evan Rehm, Kenneth Feeley. 2025. *A database of plant heat tolerances and methodological matters*. bioRxiv 2025.09.14.676187. DOI: [https://doi.org/10.1101/2025.09.14.676187](https://doi.org/10.1101/2025.09.14.676187)

## License

This dataset is a synthesis of data extracted from published academic literature. All trait values are attributed to their original sources as documented in the database.

This compilation is licensed under the [Creative Commons Attribution-NonCommercial 4.0 International License (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/).
